namespace: namespace-ns

# vegetable-app deployment values

replicas: 2
deployment:
  labels:
    app: vegetable
  name: vegetable-container
  port: 3000

image:
  repository: gowrish006/vegetable-app
  tag: latest


# vegetable-app svc values

service:
  app: vegetable
  port: 80
  type: LoadBalancer


# vegetable-app configmap values

config:
  mongoUrl: mongodb://mongo:27017/vegetableDB
  port: "3000"
  sessionSecret: vegetable-secret
  mongoDatabase: vegetableDB


# mongo statefulset values

mongo:
  name: mongo
  serviceName: mongo
  replicas: 1
  containerName: mongo
  image: mongo:6
  port: 27017
  labels:
    app: mongo


# storage class values

storage:
  name: retail-sc
  provisioner: ebs.csi.aws.com
  type: gp3
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer


# pvc values

pvc:
  name: mongo-pvc
  accessMode: ReadWriteOnce
  size: 2Gi
