apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.name }}
provisioner: {{ .Values.storage.provisioner }}
parameters:
  type: {{ .Values.storage.type }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
