apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  MONGO_URL: "{{ .Values.config.mongoUrl }}"
  PORT: "{{ .Values.config.port }}"
  SESSION_SECRET: "{{ .Values.config.sessionSecret }}"
  MONGO_INITDB_DATABASE: "{{ .Values.config.mongoDatabase }}"
